version: "3"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - 9000:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_postgres:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - ~/datos/sonar/conf:/opt/sonarqube/conf
      - ~/datos/sonar/data:/opt/sonarqube/data
      - ~/datos/sonar/extensions:/opt/sonarqube/extensions
      - ~/datos/sonar/plugins:/opt/sonarqube/lib/bundled-plugins
  sonarqube_postgres:
    container_name: sonarqube_postgres
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ~/datos/sonar/postgresql_data:/var/lib/postgresql/data
